### ISSUE TITLE
Trying to understand how I could use this on a Linux host...

### ISSUE THREAD

**Issue by nessamurmur** [bellycard/docker-loadbalancer#5]
In the event that I'm running docker on my local host and not a vm I'm not sure how to get this running... 10.0.2.15 is the ip of your host over virtualbox's interface? Not sure what IP consul should be advertising...

**Comment by funkytaco** [comment]
Any way to set that advertised IP via docker-compose? I'm using the free beta Docker Swarm "Carina" by Rackspace. For now, I hardcoded the IP of the Docker Swarm, but I have it set to one node right now, and am thinking this might not work with more nodes, possibly...
